/*
 * generated by Xtext 2.11.0.RC2
 */
package com.github.jmodel.mapper.plugin.ide


/**
 * Use this class to register ide components.
 */
class MappingLanguageIdeModule extends AbstractMappingLanguageIdeModule {
}
