/*
 * generated by Xtext 2.12.0
 */
package com.github.jmodel.mapper.plugin


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MappingLanguageStandaloneSetup extends MappingLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new MappingLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
