/*
 * generated by Xtext 2.12.0
 */
package com.github.jmodel.mapper.plugin

import org.eclipse.xtext.xbase.compiler.XbaseCompiler
import com.github.jmodel.mapper.plugin.jvmmodel.MappingXbaseCompiler

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MappingLanguageRuntimeModule extends AbstractMappingLanguageRuntimeModule {

	def Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return MappingXbaseCompiler
	}

}
