/*
 * generated by Xtext
 */
package com.github.jmodel.mapper.plugin.ui.contentassist


/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MappingLanguageProposalProvider extends AbstractMappingLanguageProposalProvider {
}
